services:
  web:
    build: ./Web
    image: chxtima/image-frontend-goodwaste:lastest
    ports:
      - "8081:80"
    container_name: frontend
  server:
    build: .
    image: chxtima/image-backend-goodwaste:lastest
    ports:
      - "8000:80"
    container_name: backend
